output "id" {
  description = "Autogenerated Service Key ID"
  value       = twingate_service_account_key.this.id
}

output "is_active" {
  description = "If the value of this attribute changes to false, Terraform will destroy and recreate the resource"
  value       = twingate_service_account_key.this.is_active
}

output "token" {
  description = "Autogenerated Service Key token"
  value       = twingate_service_account_key.this.token
  sensitive   = true
}
